name: Fix and Deploy

on:
  workflow_dispatch:

jobs:
  fix-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1 — Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 — Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 — Build the project
      - name: Build project
        run: npm run build

      # Step 5 — Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
